spatial_scope_filter:
  #
  # Filter and sort the metrics according to CORDEX domain
  #
  EUR:
    - Global
    - NH
    - EUR
    - MED+NEU+CEU
    - NEU
    - CEU
    - WCE # Western and Central Europe
    - MED
    - NBS # Norwegian and Barents Sea
    - BAL # Baltic Sea
    - BLK # Black Sea
    - NAtl # Nordic Atlantic
    - SNA # (Southern) North Atlantic
    - special # especial scope (e.g. for resolution or complexity) last

  AUS:
    - Global
    - SH
    - AUS
    - NAU
    - CAU
    - SAU
    - EAU
    - NZ
    - special

preferred: # Not implemented
  plausible_values_source: eurocordex_gcm_selection_team
  classes_source: eurocordex_gcm_selection_team
