spatial_scope_filter:
  #
  # Filter and sort the metrics according to CORDEX domain
  #
  EUR:
    - Global
    - NH
    - EUR
    - NEU
    - CEU
    - CWE
    - MED
    - NAtl # Atlantic ocean north of Scandinavia
    - BNS  # Baltic and North Sea
  AUS:
    - Global
    - SH
    - AUS
    - NAU
    - CAU
    - SAU
    - EAU
    - NZ

preferred: # Not implemented
  plausible_values_source: eurocordex_gcm_selection_team
  classes_source: eurocordex_gcm_selection_team
