spatial_scope_filter:
  #
  # Filter and sort the metrics according to CORDEX domain
  #
  EUR:
    - Global
    - NH
    - EUR
    - MED+NEU+CEU
    - NEU
    - CEU
    - CWE
    - MED
    - NBS # Norwegian and Barents Sea
    - BAL # Baltic Sea
    - special # especial scope (e.g. for resolution or complexity) last
  AUS:
    - Global
    - SH
    - AUS
    - NAU
    - CAU
    - SAU
    - EAU
    - NZ
    - special

preferred: # Not implemented
  plausible_values_source: eurocordex_gcm_selection_team
  classes_source: eurocordex_gcm_selection_team
